var chai = require('chai');
var assert = chai.assert;
var Card = require('../Card.js');
var Hand = require('../Hand.js');

describe('Hand', () => {
    describe('constructor', () => {
        it('should make a take an array of Cards to construct the hand', () => {
            let hand;
            assert.doesNotThrow(() => hand = new Hand(), Error);
            assert.doesNotThrow(() => hand = new Hand([new Card('Ten', 'Diamonds'), new Card('Ace', 'Spades')]), Error);
        });
    });
    describe('#isLessThan(Hand)', () => {
        it('should correctly evaluate if the poker hand has less value than the given poker hand', () => {
            var royalFlush = [new Card('Ace', 'Hearts'), 
                            new Card('King', 'Hearts'), 
                            new Card('Queen', 'Hearts'), 
                            new Card('Jack', 'Hearts'), 
                            new Card('Ten', 'Hearts'),
                            new Card('Two', 'Spades'),
                            new Card('Three', 'Spades')];
            var highStraightFlush = [new Card('King', 'Hearts'), 
                                    new Card('Queen', 'Hearts'), 
                                    new Card('Jack', 'Hearts'), 
                                    new Card('Ten', 'Hearts'),
                                    new Card('Nine', 'Hearts'),
                                    new Card('Two', 'Spades'),
                                    new Card('Three', 'Spades')];
            var lowStraightFlush = [new Card('Queen', 'Hearts'), 
                                new Card('Jack', 'Hearts'), 
                                new Card('Ten', 'Hearts'),
                                new Card('Nine', 'Hearts'),
                                new Card('Eight', 'Hearts'),
                                new Card('Two', 'Spades'),
                                new Card('Three', 'Spades')];
            var quadSetHigh = [new Card('King', 'Hearts'),
                            new Card('King', 'Clubs'),
                            new Card('King', 'Spades'),
                            new Card('King', 'Diamonds'),
                            new Card('Queen', 'Hearts'),
                            new Card('Jack', 'Diamonds'),
                            new Card('Ten', 'Spades')];
            var quadSetLow = [new Card('Nine', 'Hearts'),
                            new Card('Nine', 'Clubs'),
                            new Card('Nine', 'Spades'),
                            new Card('Nine', 'Diamonds'),
                            new Card('Queen', 'Hearts'),
                            new Card('Jack', 'Diamonds'),
                            new Card('Ten', 'Spades')];
            var quadKickerHigh = [new Card('Eight', 'Hearts'),
                            new Card('Eight', 'Clubs'),
                            new Card('Eight', 'Spades'),
                            new Card('Eight', 'Diamonds'),
                            new Card('Ace', 'Hearts'),
                            new Card('Jack', 'Diamonds'),
                            new Card('Ten', 'Spades')];
            var quadKickerLow = [new Card('Eight', 'Hearts'),
                            new Card('Eight', 'Clubs'),
                            new Card('Eight', 'Spades'),
                            new Card('Eight', 'Diamonds'),
                            new Card('Queen', 'Hearts'),
                            new Card('Jack', 'Diamonds'),
                            new Card('Ten', 'Spades')];
            var fullHouseHigh = [new Card('Ace', 'Hearts'),
                                new Card('Ace', 'Diamonds'),
                                new Card('Ace', 'Spades'),
                                new Card('King', 'Hearts'),
                                new Card('King', 'Spades'),
                                new Card('Four', 'Diamonds'),
                                new Card('Three', 'Hearts')];
            var fullHouseLow = [new Card('Queen', 'Hearts'),
                                new Card('Queen', 'Diamonds'),
                                new Card('Queen', 'Spades'),
                                new Card('King', 'Hearts'),
                                new Card('King', 'Spades'),
                                new Card('Four', 'Diamonds'),
                                new Card('Three', 'Hearts')];
            var fullHouseKickerHigh = [new Card('Seven', 'Hearts'),
                                    new Card('Seven', 'Diamonds'),
                                    new Card('Seven', 'Spades'),
                                    new Card('King', 'Hearts'),
                                    new Card('King', 'Spades'),
                                    new Card('Four', 'Diamonds'),
                                    new Card('Three', 'Hearts')];
            var fullHouseKickerLow = [new Card('Seven', 'Hearts'),
                                    new Card('Seven', 'Diamonds'),
                                    new Card('Seven', 'Spades'),
                                    new Card('Nine', 'Hearts'),
                                    new Card('Nine', 'Spades'),
                                    new Card('Four', 'Diamonds'),
                                    new Card('Three', 'Hearts')];
            var flushHigh = [new Card('Ace', 'Hearts'),
                            new Card('Queen', 'Hearts'),
                            new Card('Ten', 'Hearts'),
                            new Card('Eight', 'Hearts'),
                            new Card('Seven', 'Hearts'),
                            new Card('Ace', 'Clubs'),
                            new Card('Four', 'Clubs')];
            var flushLow = [new Card('King', 'Hearts'),
                            new Card('Queen', 'Hearts'),
                            new Card('Ten', 'Hearts'),
                            new Card('Eight', 'Hearts'),
                            new Card('Seven', 'Hearts'),
                            new Card('Ace', 'Clubs'),
                            new Card('Four', 'Clubs')];
            var flushKicker1High = [new Card('Queen', 'Hearts'),
                                new Card('Jack', 'Hearts'),
                                new Card('Ten', 'Hearts'),
                                new Card('Eight', 'Hearts'),
                                new Card('Seven', 'Hearts'),
                                new Card('Ace', 'Clubs'),
                                new Card('Four', 'Clubs')];
            var flushKicker1Low = [new Card('Queen', 'Hearts'),
                                new Card('Two', 'Hearts'),
                                new Card('Ten', 'Hearts'),
                                new Card('Eight', 'Hearts'),
                                new Card('Seven', 'Hearts'),
                                new Card('Ace', 'Clubs'),
                                new Card('Four', 'Clubs')];
            var flushKicker2High = [new Card('Jack', 'Hearts'),
                                new Card('Ten', 'Hearts'),
                                new Card('Eight', 'Hearts'),
                                new Card('Seven', 'Hearts'),
                                new Card('Two', 'Hearts'),
                                new Card('Ace', 'Clubs'),
                                new Card('Four', 'Clubs')];
            var flushKicker2Low = [new Card('Jack', 'Hearts'),
                                new Card('Ten', 'Hearts'),
                                new Card('Seven', 'Hearts'),
                                new Card('Four', 'Hearts'),
                                new Card('Two', 'Hearts'),
                                new Card('Ace', 'Clubs'),
                                new Card('Four', 'Clubs')];
            var flushKicker3High = [new Card('Ten', 'Hearts'),
                                new Card('Nine', 'Hearts'),
                                new Card('Eight', 'Hearts'),
                                new Card('Six', 'Hearts'),
                                new Card('Two', 'Hearts'),
                                new Card('Ace', 'Clubs'),
                                new Card('Four', 'Clubs')];
            var flushKicker3Low = [new Card('Ten', 'Hearts'),
                                new Card('Nine', 'Hearts'),
                                new Card('Eight', 'Hearts'),
                                new Card('Five', 'Hearts'),
                                new Card('Two', 'Hearts'),
                                new Card('Ace', 'Clubs'),
                                new Card('Four', 'Clubs')];
            var flushKicker4High = [new Card('Nine', 'Hearts'),
                                new Card('Eight', 'Hearts'),
                                new Card('Seven', 'Hearts'),
                                new Card('Six', 'Hearts'),
                                new Card('Four', 'Hearts'),
                                new Card('Ace', 'Clubs'),
                                new Card('Four', 'Clubs')];
            var flushKicker4Low = [new Card('Nine', 'Hearts'),
                                new Card('Eight', 'Hearts'),
                                new Card('Seven', 'Hearts'),
                                new Card('Six', 'Hearts'),
                                new Card('Three', 'Hearts'),
                                new Card('Ace', 'Clubs'),
                                new Card('Four', 'Clubs')];
            var straightHigh = [new Card('Ace', 'Hearts'),
                                new Card('King', 'Spades'),
                                new Card('Queen', 'Clubs'),
                                new Card('Jack', 'Diamonds'),
                                new Card('Ten', 'Hearts'),
                                new Card('Four', 'Spades'),
                                new Card('Seven', 'Clubs')];
            var straightLow = [new Card('King', 'Spades'),
                                new Card('Queen', 'Clubs'),
                                new Card('Jack', 'Diamonds'),
                                new Card('Ten', 'Hearts'),
                                new Card('Nine', 'Spades'),
                                new Card('Four', 'Spades'),
                                new Card('Seven', 'Clubs')];
            var tripleHigh = [new Card('Ace', 'Spades'),
                            new Card('Ace', 'Clubs'),
                            new Card('Ace', 'Diamonds'),
                            new Card('Ten', 'Hearts'),
                            new Card('Nine', 'Spades'),
                            new Card('Four', 'Spades'),
                            new Card('Seven', 'Clubs')];
            var tripleLow = [new Card('King', 'Spades'),
                            new Card('King', 'Clubs'),
                            new Card('King', 'Diamonds'),
                            new Card('Ten', 'Hearts'),
                            new Card('Nine', 'Spades'),
                            new Card('Four', 'Spades'),
                            new Card('Seven', 'Clubs')];
            var tripleKicker1High = [new Card('Queen', 'Spades'),
                                new Card('Queen', 'Clubs'),
                                new Card('Queen', 'Diamonds'),
                                new Card('Ten', 'Hearts'),
                                new Card('Nine', 'Spades'),
                                new Card('Four', 'Spades'),
                                new Card('Seven', 'Clubs')];
            var tripleKicker1Low = [new Card('Queen', 'Spades'),
                                new Card('Queen', 'Clubs'),
                                new Card('Queen', 'Diamonds'),
                                new Card('Nine', 'Spades'),
                                new Card('Two', 'Hearts'),
                                new Card('Four', 'Spades'),
                                new Card('Seven', 'Clubs')];
            var tripleKicker2High = [new Card('Jack', 'Spades'),
                                new Card('Jack', 'Clubs'),
                                new Card('Jack', 'Diamonds'),
                                new Card('Ten', 'Hearts'),
                                new Card('Nine', 'Spades'),
                                new Card('Four', 'Spades'),
                                new Card('Seven', 'Clubs')];
            var tripleKicker2Low = [new Card('Jack', 'Spades'),
                                new Card('Jack', 'Clubs'),
                                new Card('Jack', 'Diamonds'),
                                new Card('Ten', 'Hearts'),
                                new Card('Seven', 'Clubs'),
                                new Card('Two', 'Spades'),
                                new Card('Four', 'Spades')];
            var twoPairHigh = [new Card('Ace', 'Spades'),
                            new Card('Ace', 'Clubs'),
                            new Card('Queen', 'Diamonds'),
                            new Card('Queen', 'Hearts'),
                            new Card('Seven', 'Clubs'),
                            new Card('Two', 'Spades'),
                            new Card('Four', 'Spades')];
            var twoPairLow = [new Card('King', 'Spades'),
                            new Card('King', 'Clubs'),
                            new Card('Queen', 'Diamonds'),
                            new Card('Queen', 'Hearts'),
                            new Card('Seven', 'Clubs'),
                            new Card('Two', 'Spades'),
                            new Card('Four', 'Spades')];
            var twoPairKicker1High = [new Card('Queen', 'Spades'),
                                    new Card('Queen', 'Clubs'),
                                    new Card('Jack', 'Diamonds'),
                                    new Card('Jack', 'Hearts'),
                                    new Card('Seven', 'Clubs'),
                                    new Card('Two', 'Spades'),
                                    new Card('Four', 'Spades')];
            var twoPairKicker1Low = [new Card('Queen', 'Spades'),
                                    new Card('Queen', 'Clubs'),
                                    new Card('Ten', 'Diamonds'),
                                    new Card('Ten', 'Hearts'),
                                    new Card('Seven', 'Clubs'),
                                    new Card('Two', 'Spades'),
                                    new Card('Four', 'Spades')];
            var twoPairKicker2High = [new Card('Jack', 'Spades'),
                                    new Card('Jack', 'Clubs'),
                                    new Card('Ten', 'Diamonds'),
                                    new Card('Ten', 'Hearts'),
                                    new Card('Seven', 'Clubs'),
                                    new Card('Two', 'Spades'),
                                    new Card('Four', 'Spades')];
            var twoPairKicker2Low = [new Card('Jack', 'Spades'),
                                    new Card('Jack', 'Clubs'),
                                    new Card('Ten', 'Diamonds'),
                                    new Card('Ten', 'Hearts'),
                                    new Card('Four', 'Spades'),
                                    new Card('Three', 'Clubs'),
                                    new Card('Two', 'Spades')];
            var pairHigh = [new Card('Ace', 'Spades'),
                            new Card('Ace', 'Clubs'),
                            new Card('Ten', 'Diamonds'),
                            new Card('Queen', 'Hearts'),
                            new Card('Four', 'Spades'),
                            new Card('Three', 'Clubs'),
                            new Card('Two', 'Spades')];
            var pairLow = [new Card('King', 'Spades'),
                            new Card('King', 'Clubs'),
                            new Card('Ten', 'Diamonds'),
                            new Card('Queen', 'Hearts'),
                            new Card('Four', 'Spades'),
                            new Card('Three', 'Clubs'),
                            new Card('Two', 'Spades')];
            var pairKicker1High = [new Card('Queen', 'Spades'),
                                new Card('Queen', 'Clubs'),
                                new Card('Jack', 'Diamonds'),
                                new Card('Seven', 'Hearts'),
                                new Card('Four', 'Spades'),
                                new Card('Three', 'Clubs'),
                                new Card('Two', 'Spades')];
            var pairKicker1Low = [new Card('Queen', 'Spades'),
                                new Card('Queen', 'Clubs'),
                                new Card('Ten', 'Diamonds'),
                                new Card('Seven', 'Hearts'),
                                new Card('Four', 'Spades'),
                                new Card('Three', 'Clubs'),
                                new Card('Two', 'Spades')];
            var pairKicker2High = [new Card('Jack', 'Spades'),
                                new Card('Jack', 'Clubs'),
                                new Card('Ten', 'Diamonds'),
                                new Card('Eight', 'Hearts'),
                                new Card('Four', 'Spades'),
                                new Card('Three', 'Clubs'),
                                new Card('Two', 'Spades')];
            var pairKicker2Low = [new Card('Jack', 'Spades'),
                                new Card('Jack', 'Clubs'),
                                new Card('Ten', 'Diamonds'),
                                new Card('Seven', 'Hearts'),
                                new Card('Four', 'Spades'),
                                new Card('Three', 'Clubs'),
                                new Card('Two', 'Spades')];
            var pairKicker3High = [new Card('Ten', 'Spades'),
                                new Card('Ten', 'Clubs'),
                                new Card('Nine', 'Diamonds'),
                                new Card('Eight', 'Hearts'),
                                new Card('Seven', 'Spades'),
                                new Card('Three', 'Clubs'),
                                new Card('Two', 'Spades')];
            var pairKicker3Low = [new Card('Ten', 'Spades'),
                                new Card('Ten', 'Clubs'),
                                new Card('Nine', 'Diamonds'),
                                new Card('Eight', 'Hearts'),
                                new Card('Six', 'Spades'),
                                new Card('Three', 'Clubs'),
                                new Card('Two', 'Spades')];
            var pairKicker3Low = [new Card('Ten', 'Spades'),
                                new Card('Ten', 'Clubs'),
                                new Card('Nine', 'Diamonds'),
                                new Card('Eight', 'Hearts'),
                                new Card('Six', 'Spades'),
                                new Card('Three', 'Clubs'),
                                new Card('Two', 'Spades')];
            var highCardHigh = [new Card('Ace', 'Spades'),
                                new Card('King', 'Clubs'),
                                new Card('Queen', 'Diamonds'),
                                new Card('Jack', 'Hearts'),
                                new Card('Nine', 'Spades'),
                                new Card('Eight', 'Clubs'),
                                new Card('Seven', 'Spades')];
            var highCardLow = [new Card('King', 'Clubs'),
                                new Card('Queen', 'Diamonds'),
                                new Card('Jack', 'Hearts'),
                                new Card('Nine', 'Spades'),
                                new Card('Eight', 'Clubs'),
                                new Card('Seven', 'Spades'),
                                new Card('Six', 'Spades')];
            var highKicker1 = [new Card('King', 'Clubs'),
                                new Card('Jack', 'Hearts'),
                                new Card('Nine', 'Spades'),
                                new Card('Eight', 'Clubs'),
                                new Card('Seven', 'Spades'),
                                new Card('Six', 'Spades'),
                                new Card('Two', 'Diamonds')];
            var highKicker2 = [new Card('King', 'Clubs'),
                                new Card('Jack', 'Hearts'),
                                new Card('Eight', 'Clubs'),
                                new Card('Seven', 'Spades'),
                                new Card('Six', 'Spades'),
                                new Card('Three', 'Spades'),
                                new Card('Two', 'Diamonds')];
            var highKicker3 = [new Card('King', 'Clubs'),
                                new Card('Jack', 'Hearts'),
                                new Card('Eight', 'Clubs'),
                                new Card('Six', 'Spades'),
                                new Card('Four', 'Spades'),
                                new Card('Three', 'Spades'),
                                new Card('Two', 'Diamonds')];
            var highKicker4 = [new Card('King', 'Clubs'),
                                new Card('Jack', 'Hearts'),
                                new Card('Eight', 'Clubs'),
                                new Card('Six', 'Spades'),
                                new Card('Three', 'Spades'),
                                new Card('Two', 'Diamonds')];

            var royalFlushHand = new Hand(royalFlush);
            var lowStraightFlushHand = new Hand(lowStraightFlush);
            var highStraightFlushHand = new Hand(highStraightFlush);
            var hands = [new Hand(royalFlush),
                    new Hand(highStraightFlush),
                    new Hand(lowStraightFlush),
                    new Hand(quadSetHigh),
                    new Hand(quadSetLow),
                    new Hand(quadKickerHigh),
                    new Hand(quadKickerLow),
                    new Hand(fullHouseHigh),
                    new Hand(fullHouseLow),
                    new Hand(fullHouseKickerHigh),
                    new Hand(fullHouseKickerLow),
                    new Hand(flushHigh),
                    new Hand(flushLow),
                    new Hand(flushKicker1High),
                    new Hand(flushKicker1Low),
                    new Hand(flushKicker2High),
                    new Hand(flushKicker2Low),
                    new Hand(flushKicker3High),
                    new Hand(flushKicker3Low),
                    new Hand(flushKicker4High),
                    new Hand(flushKicker4Low),
                    new Hand(straightHigh),
                    new Hand(straightLow),
                    new Hand(tripleHigh),
                    new Hand(tripleLow),
                    new Hand(tripleKicker1High),
                    new Hand(tripleKicker1Low),
                    new Hand(tripleKicker2High),
                    new Hand(tripleKicker2Low),
                    new Hand(twoPairHigh),
                    new Hand(twoPairLow),
                    new Hand(twoPairKicker1High),
                    new Hand(twoPairKicker1Low),
                    new Hand(twoPairKicker2High),
                    new Hand(twoPairKicker2Low),
                    new Hand(pairHigh),
                    new Hand(pairLow),
                    new Hand(pairKicker1High),
                    new Hand(pairKicker1Low),
                    new Hand(pairKicker2High),
                    new Hand(pairKicker2Low),
                    new Hand(pairKicker3High),
                    new Hand(pairKicker3Low),
                    new Hand(highCardHigh),
                    new Hand(highCardLow),
                    new Hand(highKicker1),
                    new Hand(highKicker2),
                    new Hand(highKicker3),
                    new Hand(highKicker4)];
                    
            for(let i = 0; i < hands.length; i++) {
                assert.isFalse(hands[i].isLessThan(hands[i]));
                for(let j = i+1; j < hands.length; j++) {
                    assert.isFalse(hands[i].isLessThan(hands[j]));
                    assert.isTrue(hands[j].isLessThan(hands[i]));
                }
            }
            
        });
    });
});